### ISSUE TITLE
Package name is misspelled in package.json

### ISSUE THREAD

**Issue by ivanjonas** [domasx2/graphql-combine-query#1]
It says "grapqhl" instead of "graphql"

**Comment by domasx2** [comment]
goddamit :man_facepalming: 
thanks for taking the time to point this out!

**Comment by ivanjonas** [comment]
Wow. You misspelled it a different way now.

**Comment by domasx2** [comment]
Unbelievable, this word is triggering dyslexia for me

**Comment by AustinAmoruso** [comment]
dysgraphia. Also thanks for the wonderful lib
